image: gitpod/workspace-full-java

tasks:
  - name: Set Java 17
    init: |
      sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-17-openjdk-amd64/bin/java 1
      sudo update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac 1
      sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
      sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
      java -version

